//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nusama.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SizeOption
    {
        public int productId { get; set; }
        public string productSize { get; set; }
        public int optionId { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
