//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nusama.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionDetail
    {
        public int transactionId { get; set; }
        public Nullable<int> productId { get; set; }
        public Nullable<int> quantity { get; set; }
        public int transactionDetailId { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual TransactionHeader TransactionHeader { get; set; }
    }
}
